import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";

const openSans = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Next.js Web Curator Test",
  description: "Generated by create next app"
};

/**
 * RootLayout Component
 *
 * Represents the root layout of the web application.
 * Renders children components within an HTML body tag with a specified language.
 * Applies Open Sans font styles to the body element.
 */
export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={openSans.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
