import type { Metadata } from "next";
import { Inter } from "next/font/google"; // Importing Inter font from Google Fonts
import "./globals.css"; // Importing global CSS styles

// Initializing Inter font with Latin subset
const inter = Inter({ subsets: ["latin"] });

// Metadata object defining title and description for the web page
export const metadata: Metadata = {
  title: "Next.js Web Curator Test",
  description: "Generated by create next app"
};

/**
 * RootLayout Component
 *
 * Represents the root layout of the web application.
 * Renders children components within an HTML body tag with a specified language.
 * Applies Inter font styles to the body element.
 */
export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* Body element with Inter font styles applied */}
      <body className={inter.className}>{children}</body>
    </html>
  );
}
